### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by slcr** [cellcortex/homebridge-yeelighter#1]
Thanks for this plugin. From what the description says, it perfectly fits my needs. 
I have two 320mm without ambient light, two 480mm ceiling light with ambient lights and a meteorite (crystal pendant). All of them with Moonlight mode. The ceiling lamps are the new ones with native homekit, which doesn't help if you can't control moonlight mode and/or the ambient lights…

Sadly, i run into an error when starting the plugin on hoobs.

```[Homebridge] [1/7/2020, 10:44:53 AM] [Yeelighter] New stripe [0x0000000007c9d404] found  at yeelight://192.168.1.204:55443
[Homebridge] [1/7/2020, 10:44:53 AM] [Yeelighter] Accessory created with UUID f3702fe0-951f-4051-868a-88efb04d067e
[Homebridge] [1/7/2020, 10:44:53 AM] [Yeelighter] light 0x0000000007c9d404 stripe created. It supports: get_prop set_default set_power toggle set_bright start_cf stop_cf set_scene cron_add cron_get cron_del set_ct_abx set_rgb set_hsv set_adjust adjust_bright adjust_ct adjust_color set_music set_name
[Homebridge] [1/7/2020, 10:44:53 AM] [Yeelighter] Creating new service of subtype 'main' and adding it
[Homebridge] [1/7/2020, 10:44:53 AM] TypeError: Cannot read property 'name' of undefined
    at new LightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:125:85)
    at new WhiteLightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:165:9)
    at new Light (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/light.js:85:28)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/index.js:57:31)
    at Discovery.emit (events.js:198:13)
    at Socket.Discovery.onMessage.response (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/yeediscovery.js:43:22)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)```

**Comment by cellcortex** [comment]
This looks like the script is not handling the 'stripe' correctly. I don't have one of those. Maybe it is categorised wrongly. WhiteLightService looks wrong since I assume this is a color stripe. Could this be the meteorite?

**Comment by slcr** [comment]
the first one was the Lightstrip Plus, this one is a YLXD41YL (320mm without ambient)

```
[Homebridge] [1/7/2020, 12:32:31 PM] [Yeelighter] New ceiling11 [0x00000000066a4495] found  at yeelight://192.168.1.217:55443
[Homebridge] [1/7/2020, 12:32:31 PM] [Yeelighter] Accessory created with UUID a0bfd406-12ac-4b08-b817-a2a7cab6e40f
[Homebridge] [1/7/2020, 12:32:31 PM] [Yeelighter] light 0x00000000066a4495 ceiling11 created. It supports: get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct
[Homebridge] [1/7/2020, 12:32:31 PM] [Yeelighter] Creating new service of subtype 'main' and adding it
[Homebridge] [1/7/2020, 12:32:31 PM] TypeError: Cannot read property 'name' of undefined
    at new LightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:125:85)
    at new WhiteLightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:165:9)
    at new Light (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/light.js:85:28)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/index.js:57:31)
    at Discovery.emit (events.js:198:13)
    at Socket.Discovery.onMessage.response (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/yeediscovery.js:43:22)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[Homebridge] [1/7/2020, 12:32:31 PM] Got SIGTERM, shutting down service...
```


Here is the complete logfile-part, as i can't really tell which one causes the error.

```
[Homebridge] [1/7/2020, 12:34:52 PM] [Yeelighter] ** Discovery Started **
[Homebridge] [1/7/2020, 12:34:52 PM] [Yeelighter] Cached ceiling20 [0x000000000798c9c8] found at yeelight://192.168.1.239:55443
[Homebridge] [1/7/2020, 12:34:52 PM] [Yeelighter] light 0x000000000798c9c8 ceiling20 created. It supports: get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct bg_set_rgb bg_set_hsv bg_set_ct_abx bg_start_cf bg_stop_cf set_scene_bundle bg_set_default bg_set_power bg_set_bright bg_set_adjust bg_adjust_bright bg_adjust_color bg_adjust_ct bg_toggle dev_toggle
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Re-using service of subtype 'main'.
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Re-using service of subtype 'background'.
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] New ceiling20 [0x000000000798ca0e] found  at yeelight://192.168.1.6:55443
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Accessory created with UUID 576e6f9b-9125-4902-adab-5215658f9bec
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] light 0x000000000798ca0e ceiling20 created. It supports: get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct bg_set_rgb bg_set_hsv bg_set_ct_abx bg_start_cf bg_stop_cf set_scene_bundle bg_set_default bg_set_power bg_set_bright bg_set_adjust bg_adjust_bright bg_adjust_color bg_adjust_ct bg_toggle dev_toggle
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Creating new service of subtype 'main' and adding it
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Creating new service of subtype 'background' and adding it
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] New ceiling10 [0x000000000652ccdf] found  at yeelight://192.168.1.216:55443
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Accessory created with UUID e128fec3-a30a-4cf3-b588-23b852c362c2
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] light 0x000000000652ccdf ceiling10 created. It supports: get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct bg_set_rgb bg_set_hsv bg_set_ct_abx bg_start_cf bg_stop_cf set_scene_bundle bg_set_default bg_set_power bg_set_bright bg_set_adjust bg_adjust_bright bg_adjust_color bg_adjust_ct bg_toggle dev_toggle
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Creating new service of subtype 'main' and adding it
[Homebridge] [1/7/2020, 12:34:53 PM] TypeError: Cannot read property 'name' of undefined
    at new LightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:125:85)
    at new WhiteLightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:165:9)
    at new Light (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/light.js:85:28)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/index.js:57:31)
    at Discovery.emit (events.js:198:13)
    at Socket.Discovery.onMessage.response (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/yeediscovery.js:43:22)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Connected 0x000000000798c9c8
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Connected 0x000000000798ca0e
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Connected 0x000000000652ccdf
[Homebridge] [1/7/2020, 12:34:53 PM] Got SIGTERM, shutting down service...
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Attributes for 0x000000000652ccdf updated {"power":true,"color_mode":2,"bright":1,"hue":0,"sat":0,"ct":2739,"bg_power":true,"bg_bright":100,"bg_hue":17,"bg_sat":94,"nl_br":0,"active_mode":0,"name":""}
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Attributes for 0x000000000798c9c8 updated {"power":true,"color_mode":2,"bright":1,"hue":0,"sat":0,"ct":2821,"bg_power":true,"bg_bright":100,"bg_hue":12,"bg_sat":96,"nl_br":0,"active_mode":0,"name":""}
[Homebridge] [1/7/2020, 12:34:53 PM] [Yeelighter] Attributes for 0x000000000798ca0e updated {"power":true,"color_mode":2,"bright":20,"hue":0,"sat":0,"ct":2999,"bg_power":true,"bg_bright":100,"bg_hue":20,"bg_sat":92,"nl_br":0,"active_mode":0,"name":""}
```

i disabled LAN Control on the lightstrip, so that can't be it anymore.

![yeelight](https://user-images.githubusercontent.com/71357/71893068-e35bb300-314a-11ea-8b04-75499dd9a1e6.png)

**Comment by cellcortex** [comment]
I added a fallback for lights that I haven't seen, yet and some handling of the 2 lights you listed above. Can you try if version 1.0.9 improves things?

**Comment by cellcortex** [comment]
Also if you could try to re-enable the lightstrip. I would hope for that to work as well...

**Comment by slcr** [comment]
![RPReplay_Final1578469291 MP4](https://user-images.githubusercontent.com/71357/71959746-b7483c80-31f3-11ea-8042-41d61f7cd346.gif)

works flawless now and it's much faster than the one i used before. Also really nice that i can separate the tiles, especially useful for the meteorite pendant, where the ambient light is much more noticeable.

Maybe interesting for the readme: i had to switch some of the lights off and on again to get them discovered. Should be the first step of troubleshooting anyways, but you never now.
