### ISSUE TITLE
Error on start ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by mironovdm** [cellcortex/homebridge-yeelighter#103]
Version: 2.4.10
```
[17/02/2022, 23:41:50] [Yeelighter] Initializing Yeelighter platform...
[17/02/2022, 23:41:50] [Yeelighter] adding 1 manual accessories
[17/02/2022, 23:41:50] [Yeelighter] Device discovery handling failed TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at YeelighterPlatform.onDeviceDiscovery (/usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:91:38)
    at YeelighterPlatform.addHardCodedAccessories (/usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:224:12)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:52:12)
    at HomebridgeAPI.emit (node:events:520:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by CJenSin** [comment]
I'm facing the exact log error message.
