### ISSUE TITLE
Error while starting Yeelighter

### ISSUE THREAD

**Issue by ronlimon** [cellcortex/homebridge-yeelighter#105]
[Yeelighter] Device discovery handling failed TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at YeelighterPlatform.onDeviceDiscovery (/usr/lib/node_modules/homebridge-yeelighter/src/platform.ts:91:38)
    at YeelighterPlatform.addHardCodedAccessories (/usr/lib/node_modules/homebridge-yeelighter/src/platform.ts:224:12)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-yeelighter/src/platform.ts:52:12)
    at HomebridgeAPI.emit (node:events:520:28)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:173:14) {
  code: 'ERR_INVALID_ARG_TYPE'

It does to work fine :)

**Comment by cembaykara** [comment]
Facing the same issue

**Comment by pedroxns** [comment]
Same issue here !

**Comment by AlexKusnezov** [comment]
same here

**Comment by cellcortex** [comment]
This looks like you have an outdated version of node. Can you update the node version that you run Homebridge with to at least 16.x?
