### ISSUE TITLE
Yeelight Bulb W3 keeps "No Respond" randomly and generates lots of "Color tempurature" characteristic error

### ISSUE THREAD

**Issue by shipham2302** [cellcortex/homebridge-yeelighter#128]
Hi guys, i just setup Homebridge and install this plugin, and it's work out of the box for quite sometimes.

**I currently have these devices:
- 4 Yeelight Bulbs Light W3
- 1 Yeelight Ceiling Light 450s
- 1 Yeelight Color Bulb**

After set everything up, it'll work for a while and randomly show 'no respond' during the day, or night. This make my whole automations completely useless. I've tried to re-install plugin, make it child-bridge, overrides configs for every lights in setting. Nothing work. 

`[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 1] getHue: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":4928,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 1] getSat: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":4928,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 2] getCT: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":4928,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} -> 203 []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 2] getHue: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":4928,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 2] getSat: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":4928,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 3] getCT: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":2703,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} -> 370 []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 3] getHue: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":2703,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [Yeelighter] [Counter Light 3] getSat: {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":100,"ct":2703,"bg_power":false,"bg_bright":0,"bg_hue":0,"bg_sat":0,"bg_ct":0,"bg_lmode":0,"nl_br":0,"active_mode":0,"name":""} []
[11/15/2022, 10:38:56 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 250 exceeded minimum of 370. See https://homebridge.io/w/JtMGR for more info.
[11/15/2022, 10:38:56 AM] [homebridge-yeelighter] Error: 
    at ColorTemperature.Characteristic.characteristicWarning (/srv/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2138:105)
    at ColorTemperature.Characteristic.validateUserInput (/srv/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2050:14)
    at /srv/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /srv/homebridge/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at ColorTemperature.<anonymous> (/srv/homebridge/lib/node_modules/homebridge-yeelighter/src/lightservice.ts:262:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

Noted that, after i setup my lights in homebridge and home app. I'll deny these devices to connect to internet using my router. Is this possible to be the reason? Can forced IP on these would help?

**Comment by Lyliya** [comment]
Hey, i think i have the same issue as you, i have 3 bulb, and only one controlled by Homebridge (old bulb that dont have Homekit integration), but after some time (2-10 hours), everything go to "No respond" and broke all my automation

Did you found a solution ? I migrated to Home Assistant just for this bulb, and i want Homebridge back 😭

**Comment by cellcortex** [comment]
I believe this should be fixed in the latest builds
