### ISSUE TITLE
Cyclic warnings in log

### ISSUE THREAD

**Issue by mrmaximas** [cellcortex/homebridge-yeelighter#25]
I'm try to using Mi Bedside Lamp with yeelighter plugin, lamp discovered and works Ok.
config is here
{
            "name": "Yeelighter",
            "ctforcolor": true,
            "nonblocking": false,
            "timeout": 5000,
            "interval": 60000,
            "platform": "Yeelighter"
        }
starting log is here

[5/8/2020, 4:46:17 PM] [Yeelighter] Cached bslamp1 [0x0000000005464227] found at yeelight://192.168.88.161:55443
[5/8/2020, 4:46:17 PM] [Yeelighter] [0x0000000005464227] Re-using service of subtype 'main'. []
[5/8/2020, 4:46:17 PM] [Yeelighter] [0x0000000005464227] installed as Color light []
[5/8/2020, 4:46:17 PM] [Yeelighter] [0x0000000005464227] Connected []
==
but the messages are constantly being displayed
}
[5/8/2020, 4:49:55 PM] [Yeelighter] [0x0000000005464227] Disconnected []
[5/8/2020, 4:50:00 PM] [Yeelighter] [0x0000000005464227] Connected []
[5/8/2020, 4:50:00 PM] [Yeelighter] [0x0000000005464227] WARN: send command but device doesn't seem reachable []
Socket Closed false
Socket Closed, reconnecting in 5s Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[5/8/2020, 4:51:00 PM] [Yeelighter] [0x0000000005464227] Disconnected []
[5/8/2020, 4:51:05 PM] [Yeelighter] [0x0000000005464227] Connected []
[5/8/2020, 4:51:05 PM] [Yeelighter] [0x0000000005464227] WARN: send command but device doesn't seem reachable []
Socket Closed false
Socket Closed, reconnecting in 5s Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[5/8/2020, 4:51:27 PM] [Yeelighter] [0x0000000005464227] Disconnected []
[5/8/2020, 4:51:33 PM] [Yeelighter] [0x0000000005464227] Connected []
[5/8/2020, 4:51:33 PM] [Yeelighter] [0x0000000005464227] WARN: send command but device doesn't seem reachable []
Socket Closed false
Socket Closed, reconnecting in 5s Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
[5/8/2020, 4:52:27 PM] [Yeelighter] [0x0000000005464227] Disconnected []
[5/8/2020, 4:52:33 PM] [Yeelighter] [0x0000000005464227] Connected []
[5/8/2020, 4:52:33 PM] [Yeelighter] [0x0000000005464227] WARN: send command but device doesn't seem reachable []
Socket Closed false
Socket Closed, reconnecting in 5s Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'

==
what am I doing wrong?

**Comment by cellcortex** [comment]
fixed in 1.3.0

**Comment by mrmaximas** [comment]
thanks
