### ISSUE TITLE
Stripe issues: TypeError: Cannot read property 'saveDefault' of null

### ISSUE THREAD

**Issue by slcr** [cellcortex/homebridge-yeelighter#3]
I have new issues with the Lightstrip Plus in Version 1.2.23:

```
[Homebridge] [1/15/2020, 8:59:13 AM] [homebridge-yeelighter.Yeelighter] Cached stripe [0x0000000007c9d404] found at yeelight://192.168.1.204:55443
[Homebridge] [1/15/2020, 8:59:13 AM] TypeError: Cannot read property 'saveDefault' of null
    at new LightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:230:44)
    at new ColorLightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/colorlightservice.js:6:9)
    at new Light (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/light.js:148:32)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/index.js:66:31)
    at Discovery.emit (events.js:198:13)
    at Socket.Discovery.onMessage.response (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/yeediscovery.js:43:22)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[Homebridge] [1/15/2020, 8:59:13 AM] [homebridge-yeelighter.Yeelighter] Cached ceiling11 [0x00000000066a4346] found at yeelight://192.168.1.215:55443
[Homebridge] [1/15/2020, 8:59:13 AM] TypeError: Cannot read property 'saveDefault' of null
    at new LightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/lightservice.js:230:44)
    at new TemperatureLightService (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/temperaturelightservice.js:6:9)
    at new Light (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/light.js:157:36)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/index.js:66:31)
    at Discovery.emit (events.js:198:13)
    at Socket.Discovery.onMessage.response (/home/hoobs/.hoobs/node_modules/homebridge-yeelighter/dist/yeediscovery.js:43:22)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
[Homebridge] [1/15/2020, 8:59:14 AM] Got SIGTERM, shutting down service...
```

`ceiling11 ` is a YLXD41YL (320mm, homekit, white range)

**Comment by dmitryivtec** [comment]
разве эта лента не добавляется напрямую в Homekit, без Homebridge? Она залетает без плагинов (через Mi Home).
