### ISSUE TITLE
ignoring lights creates an error

### ISSUE THREAD

**Issue by nitaybz** [cellcortex/homebridge-yeelighter#53]
Great plugin, thanks!

However.. I'm getting this error when ignoring specific light in the config

```
[02/12/2020, 11:38:07] [Yeelighter] Override config for 0x000000000796XXX: {"id":"0x0000000007968XXX","useNameAsId":false,"ignored":true}
[02/12/2020, 11:38:07] [Yeelighter] Ignoring 0x0000000007968XXX as configured. Removing from cache.
[02/12/2020, 11:38:07] ReferenceError: Cannot access 'uuid' before initialization
    at /usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:67:93
    at Array.find (<anonymous>)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:67:56)
    at Discovery.emit (events.js:315:20)
    at Socket.Discovery.onMessage (/usr/local/lib/node_modules/homebridge-yeelighter/src/discovery.ts:69:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[02/12/2020, 11:38:07] [Yeelighter] Override config for 0x0000000007968XXX: {"id":"0x0000000007968XXX","useNameAsId":false,"ignored":true}
[02/12/2020, 11:38:07] [Yeelighter] Ignoring 0x0000000007968XXX as configured. Removing from cache.
[02/12/2020, 11:38:07] ReferenceError: Cannot access 'uuid' before initialization
    at /usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:67:93
    at Array.find (<anonymous>)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/usr/local/lib/node_modules/homebridge-yeelighter/src/platform.ts:67:56)
    at Discovery.emit (events.js:315:20)
    at Socket.Discovery.onMessage (/usr/local/lib/node_modules/homebridge-yeelighter/src/discovery.ts:69:12)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
```

**Comment by cellcortex** [comment]
fixed.
