### ISSUE TITLE
Fixed IP address?

### ISSUE THREAD

**Issue by spam667** [cellcortex/homebridge-yeelighter#58]
Hello!

I'm sorry because I don't know if opening a ticket is the best way to communicate with you about yeelighter. If this is not an issue, please feel free to close it and let me know how to communicate correctly.

My question is if there is possible to set a fixed IP address for bulbs in Yeelighter.

I have several VLAN's and a Firewall between my network devices and my IoT devices. I noticed that yeelighter works using multicast to "find" the bulbs, but in my case, the Homebridge is on a different VLAN so multicast is not passing from Homebridge network to IoT network.

I have Avahi running for mDNS to work, but I noticed that yeelighter is using traditional multicast so I don't know if I build some PIM package on my pfsense firewall I could make this to work.

Anyway, do you think that it could be possible to "fix" the IP address of a bulb/lamp on yeelighter? For me it could do the trick 👍 

Thanks!

**Comment by S474N** [comment]
Same problem as me :)

https://github.com/cellcortex/homebridge-yeelighter/issues/24#issuecomment-625794597

EDIT: but in Settings of this plugin is new option - "**Force IP Address**", which add `"address": "192.168.xxx.xxx"` to config.json 

But this option doesn't really work. @cellcortex will it works? Thank you for reply.

![image](https://user-images.githubusercontent.com/16512337/102385099-b86e1600-3fcd-11eb-807b-a24873c66e0b.png)

**Comment by cellcortex** [comment]
With the changes to 2.x I should now be able to add functionality to manually add lights with IP address. It won't be pretty - you will have to manually put all the lights data into the config since that's what is part of the discover response but it should work.
I hope to find some time over the holidays.

**Comment by S474N** [comment]
@cellcortex I edited my last post and you are here! :) 

What needs to be filled out?

**Comment by cellcortex** [comment]
So just to be clear, this is not working yet. I added the option as a first step to allow me development. With the discovery, the lights return information which is used to configure the homebridge plugin. This information will have to be manually put into the config. This is the internal structure that needs to be filled:
```
{
  location: string;
  id: string;
  model: string;
  support: string;
  fw_ver: string;
}
```

**This is Work in Progress and not yet working!** I'll announce here once I have something worth testing...

**Comment by S474N** [comment]
Ok, will wait (also for sample "payload")

**Comment by spam667** [comment]
Hey!! Some movement here :) Thank you both very much for your answers and cellcortex for your work!!

Thank you! I'll be waiting for the update! I am trying also to route multicast across my pfsense to solve the issue other way around, or go to use containers with VLAN's to create a container with homebridge on the same VLAN and forget about multicast issues :)

But any option is always welcome!

BR!

**Comment by spam667** [comment]
Also if you need "beta testing", please, ask for help :) and I'll try to do some tests for you.

I only have one Mi Desk Lamp, but I could test using it!

Thanks again !!

**Comment by RomanLotsmanov** [comment]
Hi, I am also use different VLAN and when I add devices by ip I see many errors:
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string

testing 2 device: LED strip and Desk Lamp
{
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": false,
            "manual": [
                {
                    "id": "0x0000000012ce12a8",
                    "address": "192.168.100.177",
                    "name": "strip",
                    "log": true
                }
            ],
            "platform": "Yeelighter"
        }

**Comment by S474N** [comment]
@RomanLotsmanov it's ok, because there is not yet support for IP address :D

**Comment by maxnowack** [comment]
Is there any update on this? Or at least a workaround to get the yeelights into hombebridge in an environment where auto discovery doesn't work?

**Comment by S474N** [comment]
It's new version of plugin:
https://github.com/cellcortex/homebridge-yeelighter/commit/860c49a1dc4fcfc3e86fd384cf095149dc6bdd42

But for me not working.

**Comment by S474N** [comment]
@cellcortex can we test this experimental function? If yes, how pls?

**Comment by prawnPANDI** [comment]
Tested with Manually adding Bulb since my network is having issues with Multicast. Doesn't work at the moment. Here are my config and log files. 

Config
`        {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": false,
            "blocking": false,
            "split": true,
            "manual": [
                {
                    "id": "DELETED FOR PRIVACY",
                    "address": "DELETED FOR PRIVACY",
                    "name": "Lamp",
                    "model": "color4",
                    "support": "get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx adjust_ct set_name set_adjust adjust_bright adjust_color set_rgb set_hsv set_music udp_sess_new udp_sess_keep_alive udp_chroma_sess_new",
                    "log": true
                }
            ],
            "platform": "Yeelighter"`
       

Error Logs

[1/27/2022, 12:44:53 AM] [Config] Running in Service Mode
[1/27/2022, 12:44:53 AM] [AmbiClimatePlatform] Initializing AmbiClimatePlatform platform...
[1/27/2022, 12:44:53 AM] [Yeelighter] Initializing Yeelighter platform...
[1/27/2022, 12:44:54 AM] [Yeelighter] adding 1 manual accessories
[1/27/2022, 12:44:54 AM] [Yeelighter] New color4 [0x000000001244dcad] found at yeelight://192.168.1.14
[1/27/2022, 12:44:54 AM] [Yeelighter] Loading accessory from cache: 0x000000001244dcad (color4)
[1/27/2022, 12:44:54 AM] [Yeelighter] Accessory created with UUID 534e5cb6-09a4-4344-82ff-bbdeec2409f8
[1/27/2022, 12:44:54 AM] [Yeelighter] [0x000000001244dcad] no subtype []
[0x000000001244dcad@@Configured Name] Characteristic not in required or optional characteristic section for service Lightbulb. Adding anyway.
[1/27/2022, 12:44:54 AM] [Yeelighter] [0x000000001244dcad] installed as Color light []
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
[1/27/2022, 12:44:56 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:44:56 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:44:56 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
[1/27/2022, 12:45:05 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:05 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:05 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
[1/27/2022, 12:45:11 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:11 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:11 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
[1/27/2022, 12:45:21 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:21 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/27/2022, 12:45:21 AM] [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string

**Comment by S474N** [comment]
Also tested with newest version of plugin - 2.4.10 and Yeelight 650:

**Config:**
```
    "platforms": [
        {
            "platform": "Yeelighter",
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": false,
            "manual": [
                {
                    "id": "0x000000000xxxxxx",
                    "address": "192.x.x.x",
                    "name": "Sedacka",
                    "model": "ceiling4",
                    "log": true,
                    "backgroundLight": true,
                    "nightLight": true,
                    "separateAmbient": false,
                    "ignorePower": false
                }
            ]
        },
```

**Log:**
```
[2/8/2022, 7:22:23 PM] [Yeelighter] adding 1 manual accessories
[2/8/2022, 7:22:23 PM] [Yeelighter] New ceiling4 [0x000000000XXXXX] found at yeelight://192.x.x.x
[2/8/2022, 7:22:23 PM] [Yeelighter] Loading accessory from cache: 0x000000000XXXXX(ceiling4)
[2/8/2022, 7:22:23 PM] [Yeelighter] Accessory created with UUID 0xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
[2/8/2022, 7:22:23 PM] [Yeelighter] Device discovery handling failed TypeError: Cannot read properties of undefined (reading 'split')
    at new YeeAccessory (/homebridge/node_modules/homebridge-yeelighter/src/yeeaccessory.ts:107:40)
    at Function.instance (/homebridge/node_modules/homebridge-yeelighter/src/yeeaccessory.ts:91:15)
    at YeelighterPlatform.onDeviceDiscovery (/homebridge/node_modules/homebridge-yeelighter/src/platform.ts:205:22)
    at YeelighterPlatform.addHardCodedAccessories (/homebridge/node_modules/homebridge-yeelighter/src/platform.ts:224:12)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-yeelighter/src/platform.ts:52:12)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```

Can @cellcortex show example of correct config? Thank you!


EDIT: after adding same `support` as @prawnPANDI, have same error as he.

**Comment by spam667** [comment]
> 

Hello S474N,

not cellcortex, but I'll try to help you.

The code you pasted is like an example, you have to fill it with your OWN values.

For example this section, you have to set your own values:

                    "id": "0x000000000xxxxxx",
                    "address": "192.x.x.x",
                    "name": "Sedacka",
                    "model": "ceiling4",

To obtain the ID you have to check on google "how to extract ID from Xiaomi devices". I did retrieved the ID of my Mi Desk Lamp but I don't really remember how, there are several ways to achieve it depending if you are using Android, iOS, etc.

The "address" it's your OWN IP address, the "x" characters are supposed to be modified. You have to check which IP address is your device using into your network and set the value to this IP address. For example it will be something like 192.168.0.217. You have to obtain the IP and set the value.

name and model I assume that are text values but don't really know if they have impact or no. I assume the "name" field is the name you will see into the Home app.

BR!

**Comment by xtianpaiva** [comment]
Hi, having same issue with plug-in v2.5.2, Homebridge (v1.4.0) in main LAN, Yeelight in IoT VLAN, no multicast, so manual config would be great!

>Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string
Socket Closed with error "Error" getaddrinfo ENOTFOUND string

>
         {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": false,
            "manual": [
                {
                    "id": "0x000000000xxxxxxx",
                    "address": "192.168.50.xx",
                    "name": "Velador",
                    "model": "mono",
                    "support": "get_prop set_default set_power toggle set_bright start_cf stop_cf set_scene cron_add cron_get cron_del set_adjust set_name",
                    "colorTemperature": {
                        "min": 5000,
                        "max": 5000
                    },
                    "ignorePower": false
                }
            ],
            "platform": "Yeelighter"
        }

**Comment by ghost** [comment]
I have this issue with multiple ip 
Lamp do not work and i edit plugin in files discovery.js and yeediscovery.js
I add line  this.socket.setMulticastInterface('10.0.0.254');

        this.socket.bind(options.port, () => {
            this.socket.setBroadcast(true);
            this.socket.setMulticastInterface('10.0.0.254');
            this.socket.setMulticastTTL(128);
            this.socket.addMembership(options.multicastAddr);
        });
