### ISSUE TITLE
2.3.6: Errors

### ISSUE THREAD

**Issue by atr00** [cellcortex/homebridge-yeelighter#60]
Hi,

Following update 2.3.6, all lights stopped working. I have removed the previous ones from the cache and restarted HomeBridge. Getting this error:

[12/13/2020, 3:23:01 AM] [Yeelighter] [0x00000000079798c9] Error returned for request [5]: {"code":-1,"message":"client quota exceeded"} []
(node:417) UnhandledPromiseRejectionWarning: #<Object>
(node:417) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by atr00** [comment]
Got some other error:
[12/13/2020, 8:37:51 AM] [Yeelighter] Loading accessory from cache: 0x00000000101cc163 (ceiling20)
(node:952) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

**Comment by atr00** [comment]
I removed again from the cache after I have deactivated the LAN mode. When I reactive the LAN mode, it makes Homebridge crash with this error:

[12/13/2020, 9:07:02 AM] [Yeelighter] New ceiling20 [0x00000000101d46fb] found at yeelight://192.168.1.119:55443
[12/13/2020, 9:07:02 AM] [Yeelighter] Accessory created with UUID d33d4e17-75a0-44a3-b3a3-644a0fe81bfb
[12/13/2020, 9:07:02 AM] [Yeelighter] Separate Ambient Accessory created with UUID 56e1151c-6747-4cdd-b14b-c7fefd2956d7
[12/13/2020, 9:07:02 AM] [Yeelighter] [0x00000000101d46fb] no subtype []
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/13/2020, 9:07:02 AM] [Yeelighter] [0x00000000101d46fb#background] registering subtype 0x00000000101d46fb#background []
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/13/2020, 9:07:02 AM] [Yeelighter] [0x00000000101d46fb] installed as Color temperature light with ambience light []
[12/13/2020, 9:07:02 AM] [Yeelighter] [0x00000000101d46fb] ceiling20 Connected []
[12/13/2020, 9:07:02 AM] [Yeelighter] [0x00000000101d46fb] temperature light updated {"power":false,"color_mode":2,"bright":28,"hue":0,"sat":0,"ct":2700,"bg_power":false,"bg_bright":100,"bg_hue":15,"bg_sat":100,"bg_ct":4000,"bg_lmode":3,"nl_br":14,"active_mode":1,"name":""} []
[12/13/2020, 9:07:05 AM] [Yeelighter] Separate Ambient Accessory not wanted anymore. Unregistering
[12/13/2020, 9:07:05 AM] [Yeelighter] New (cached) ceiling20 [0x00000000101d46fb] found at yeelight://192.168.1.119:55443
[12/13/2020, 9:07:06 AM] [Dining Room AC] Power: Off.
[12/13/2020, 9:07:06 AM] [Living Room AC] Power: On.
[12/13/2020, 9:07:06 AM] [Guest Room AC] Power: Off.
[12/13/2020, 9:07:06 AM] [Kid's Room AC] Power: Off.
[12/13/2020, 9:07:08 AM] [Yeelighter] Separate Ambient Accessory not wanted anymore. Unregistering
[12/13/2020, 9:07:08 AM] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory._this.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:472:13)
    at Bridge.Accessory._this.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:484:12)
    at Server.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:548:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:331:10)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/homebridge/node_modules/homebridge-yeelighter/src/platform.ts:108:16)
    at Discovery.emit (events.js:310:20)
    at Socket.Discovery.onMessage (/homebridge/node_modules/homebridge-yeelighter/src/discovery.ts:69:12)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8)
[12/13/2020, 9:07:08 AM] Got SIGTERM, shutting down Homebridge...
[12/13/2020, 9:07:13 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[12/13/2020, 9:07:18 AM] [HB Supervisor] Restarting Homebridge...




It seems as well to prevent the control of those lights in Yeelight App. Seems to be somehow related to the error: {"code":-1,"message":"client quota exceeded"}

**Comment by cellcortex** [comment]
Thanks for the report. I pushed an update hoping to fix this.

**Comment by atr00** [comment]
thanks. It seem that after updating to 2.3.7 the issue or part if the issue is still there:

12/14/2020, 12:26:38 AM] [Yeelighter] New ceiling20 [0x00000000101cc163] found at yeelight://192.168.1.121:55443
[12/14/2020, 12:26:38 AM] [Yeelighter] Accessory created with UUID 9c73ac9b-e534-4741-b4b1-5c7425f8cf6a
[12/14/2020, 12:26:38 AM] [Yeelighter] Separate Ambient Accessory created with UUID 7284f68c-fee3-4b44-8939-0cfc3b43cb75
[12/14/2020, 12:26:38 AM] [Yeelighter] [0x00000000101cc163] no subtype []
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/14/2020, 12:26:38 AM] [Yeelighter] [0x00000000101cc163#background] registering subtype 0x00000000101cc163#background []
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[12/14/2020, 12:26:38 AM] [Yeelighter] [0x00000000101cc163] installed as Color temperature light with ambience light []
[12/14/2020, 12:26:38 AM] [Yeelighter] [0x00000000101cc163] ceiling20 Connected []
[12/14/2020, 12:26:38 AM] [Yeelighter] [0x00000000101cc163] temperature light updated {"power":false,"color_mode":2,"bright":100,"hue":0,"sat":0,"ct":4000,"bg_power":false,"bg_bright":100,"bg_hue":1,"bg_sat":100,"bg_ct":4000,"bg_lmode":1,"nl_br":5,"active_mode":1,"name":""} []
[12/14/2020, 12:26:41 AM] [Yeelighter] Separate Ambient Accessory not wanted anymore. Unregistering
[12/14/2020, 12:26:41 AM] [Yeelighter] New (cached) ceiling20 [0x00000000101cc163] found at yeelight://192.168.1.121:55443
[12/14/2020, 12:26:44 AM] [Yeelighter] Separate Ambient Accessory not wanted anymore. Unregistering
[12/14/2020, 12:26:45 AM] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory._this.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:472:13)
    at Bridge.Accessory._this.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:484:12)
    at Server.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:548:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:331:10)
    at Discovery.YeelighterPlatform.onDeviceDiscovery (/homebridge/node_modules/homebridge-yeelighter/src/platform.ts:104:17)
    at Discovery.emit (events.js:310:20)
    at Socket.Discovery.onMessage (/homebridge/node_modules/homebridge-yeelighter/src/discovery.ts:69:12)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8)
[12/14/2020, 12:26:45 AM] Got SIGTERM, shutting down Homebridge...
[12/14/2020, 12:26:50 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by cellcortex** [comment]
I believe this is fixed in 2.3.11
