### ISSUE TITLE
cant load plug inn

### ISSUE THREAD

**Issue by Pikorek** [cellcortex/homebridge-yeelighter#97]
Hi 
It was working for a long time but now with new issue something happe - im not a programer so if you could explain in easy languge. I see from command that node.js is to low but i have 14.4 which is standard and pluginn should work above 10.

[26.01.2022, 15:12:53] The plugin "homebridge-yeelighter" requires Node.js version of >=16.6.0 which does not satisfy the current Node.js version of v14.15.4. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
[26.01.2022, 15:12:53] ====================
[26.01.2022, 15:12:53] ERROR LOADING PLUGIN homebridge-yeelighter:
[26.01.2022, 15:12:53] Error: Cannot find module 'node:events'
Require stack:
- /usr/lib/node_modules/homebridge-yeelighter/dist/yeedevice.js
- /usr/lib/node_modules/homebridge-yeelighter/dist/platform.js
- /usr/lib/node_modules/homebridge-yeelighter/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-yeelighter/src/yeedevice.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

**Comment by cellcortex** [comment]
The latest version of yeelighter depends on new versions of node and Homebridge. You will only be able to use them if you first update those. 
In case you cannot update, please use up to version 2.3.13.
